version: "3.4"

services:
    front:
        hostname: front
        container_name: front
        build:
            context: ./frontend-client
        ports:
            - 8080:3000

    api:
        hostname: api
        container_name: api
        build:
            context: ./ApiGateway
        ports:
            - 8081:80
            
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:latest
        
    postgres:
        container_name: postgres
        restart: always
        ports:
          - 5432:5432
        build:
            context: ./postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: example
            POSTGRES_DB: db

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
          - 9080:8080