version: "3.4"

services:
    front:
        hostname: front
        container_name: front
        build:
            context: ./frontend-client
        ports:
            - 8080:3000

    api:
        hostname: api
        container_name: api
        build:
            context: ./ApiGateway
        ports:
            - 8081:80
            
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        ports:
          - 5672:5672
          - 15672:15672
        
    postgres:
        container_name: postgres
        restart: always
        ports:
          - 5432:5432
        build:
            context: ./postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: example
            POSTGRES_DB: hotels

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
          - 9080:8080
          
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
        ports:
            - '27017:27017'
            
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - '8082:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
            ME_CONFIG_MONGODB_SERVER: "mongodb"
            ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"